# Makefile for HotDrink tests.

include $(MAKEDIR)/Makefile.common
include $(MAKEDIR)/Makefile.js

##################################################
# mandatory configuration

TITLE := hotdrink-parser-test

##################################################
# optional configuration

SRCDIR := test/qunit
SOURCES := \
  common/patterns.js \
	test/patterns.js \
	common/circle.js \
	parser/model.js

HEADERS := \

