# Makefile for the HotDrink parser module.

include $(MAKEDIR)/Makefile.common
include $(MAKEDIR)/Makefile.js

##################################################
# mandatory configuration

TITLE := hotdrink-parser

##################################################
# optional configuration

SRCDIR := lib
SOURCES := \
	parsec.js \
	expr_parser.js \
	model_parser.js \
	view_parser.js

HEADERS := \
  lib/utility/debug.m4.js

